# Generated by Django 3.2 on 2022-09-06 10:59

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.articlesource')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('content', tinymce.models.HTMLField()),
                ('pub_date', models.DateTimeField()),
                ('url', models.URLField(default='')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.articlesource')),
                ('tags', models.ManyToManyField(to='myapp.Tag', verbose_name='tag')),
            ],
        ),
    ]
